# Make games/<name> its own git repository (idempotent). Source, then: game_repo_init <dir> <name> "<title>"
# Tracked: game.conf, NOTES.md, README.md, notes/*.md|txt. Everything extracted from the
# cabinet (lib/, data/) and the links into shared/ are ignored — `make new` regenerates them.

game_repo_init() {
  local gd=$1 name=$2 title=$3
  [ -f "$gd/.gitignore" ] || cat > "$gd/.gitignore" <<'EOF'
# Regenerated by `make new GAME=<name>` in the main megatouch-port repo
/lib/
/data/
/runtime
/run
/megatouch-host
/player/
/var/
/decomp/
/notes/ghproj/
/notes/shots/
*.prof
*.log
EOF
  [ -f "$gd/README.md" ] || cat > "$gd/README.md" <<EOF
# $title ($name)

One game of [megatouch-port](https://github.com/${GITHUB_ORG:-Merit-Megatouch}/${MAIN_REPO:-megatouch-port}):
original Megatouch ION cabinet games running on Linux / WSL2.

This repo holds the port's configuration and notes — no cabinet code or assets. Use it from
the main repo, where it lives at \`games/$name\`:

\`\`\`
git clone --recurse-submodules https://github.com/${GITHUB_ORG:-Merit-Megatouch}/${MAIN_REPO:-megatouch-port}
cd ${MAIN_REPO:-megatouch-port} && make setup && make new GAME=$name && make run GAME=$name
\`\`\`

| File | What |
| --- | --- |
| [game.conf](game.conf) | GameId, library, asset folder, window size, language |
| [NOTES.md](NOTES.md) | Status, checklist, dated log |
| [notes/scaffold.md](notes/scaffold.md) | Facts found when scaffolding |
| [notes/unresolved.txt](notes/unresolved.txt) | Cabinet loader functions still needed |
EOF
  if [ ! -e "$gd/.git" ]; then   # a file in a submodule checkout, a folder otherwise
    git -C "$gd" init -q -b main
    # inherit the identity configured in the main repo
    local n e
    n=$(git -C "$gd/../.." config user.name || true); e=$(git -C "$gd/../.." config user.email || true)
    [ -n "$n" ] && git -C "$gd" config user.name "$n"
    [ -n "$e" ] && git -C "$gd" config user.email "$e"
    local h; h=$(git -C "$gd/../.." config credential.helper || true)
    [ -n "$h" ] && git -C "$gd" config credential.helper "$h"
    git -C "$gd" add -A
    git -C "$gd" commit -q -m "Scaffold $title ($name)" && echo "initialised git repo in games/$name"
  fi
}
