#!/bin/bash
# Build everything that is not in git. Safe to re-run: finished steps are skipped.
#
#   scripts/setup.sh            toolchain + shared runtime + cabinet data + build
#   scripts/setup.sh --ghidra   also download JDK 21 + Ghidra (≈800 MB) for tools/decompile.sh
#
# Needs (host, no root): gcc/g++ (x86-64), make, python3, curl, debugfs (e2fsprogs),
# apt-get + dpkg-deb (Ubuntu), binutils. Nothing is installed system-wide.
set -euo pipefail
R=$(cd "$(dirname "$0")/.." && pwd)
cd "$R"
. ./cabinet.conf
. scripts/lib/cabinet.sh

T=$R/toolchain            # compilers, 32-bit packages, python venv, Ghidra
S=$R/shared               # what every game links to at runtime
step() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
done_mark() { [ -f "$1/.done" ]; }
mark() { touch "$1/.done"; }

step "checking host tools"
for t in gcc g++ make python3 curl debugfs apt-get dpkg-deb readelf nm objdump; do
  command -v $t >/dev/null || { echo "missing: $t"; exit 1; }
done
GCC=$(gcc -dumpversion | cut -d. -f1)
CODENAME=$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
echo "gcc $GCC, Ubuntu $CODENAME, cabinet source: $(cab_mode)"
cab_check

# ------------------------------------------------------------------ 32-bit compiler
step "32-bit compiler support (toolchain/sysroot)"
if ! done_mark "$T/sysroot"; then
  mkdir -p "$T/cache/multilib" "$T/sysroot"
  (cd "$T/cache/multilib" && sed "s/@GCC@/$GCC/; /^#/d; /^$/d" "$R/scripts/packages/multilib.txt" | while read -r p; do
     ls "${p}"_*.deb >/dev/null 2>&1 || apt-get download "$p" >/dev/null || echo "  (skip $p)"; done)
  for d in "$T"/cache/multilib/*.deb; do dpkg-deb -x "$d" "$T/sysroot"; done
  mark "$T/sysroot"
fi
# linker scripts carry absolute paths; point them at this sysroot (also after moving the repo)
for f in libc.so libm.so libpthread.so; do
  [ -f "$T/sysroot/usr/lib32/$f" ] && grep -q GROUP "$T/sysroot/usr/lib32/$f" &&
    sed -i -E "s#[^ (]*/usr/lib32/#$T/sysroot/usr/lib32/#g; s#[^ (]*/lib/ld-linux.so.2#$T/sysroot/usr/lib32/ld-linux.so.2#g" "$T/sysroot/usr/lib32/$f"
done
cat > "$T/g++32" <<EOF
#!/bin/sh
# g++ for 32-bit (i386) using toolchain/sysroot — generated by scripts/setup.sh
SR="$T/sysroot"
exec g++ -m32 -B\$SR/usr/lib32 -B\$SR/usr/lib/gcc/x86_64-linux-gnu/$GCC/32 \\
  -L\$SR/usr/lib32 -L\$SR/usr/lib/gcc/x86_64-linux-gnu/$GCC/32 \\
  -isystem \$SR/usr/include/x86_64-linux-gnu/c++/$GCC/32 \\
  -idirafter /usr/include/x86_64-linux-gnu -idirafter \$SR/usr/include/x86_64-linux-gnu \\
  -Wl,--dynamic-linker=\$SR/usr/lib32/ld-linux.so.2 -Wl,-rpath-link,\$SR/usr/lib32 "\$@"
EOF
chmod +x "$T/g++32"

# ------------------------------------------------------------------ 32-bit SDL2 runtime
step "32-bit SDL2 runtime packages (toolchain/i386)"
if ! done_mark "$T/i386"; then
  A=$T/apt-i386
  mkdir -p "$A/lists/partial" "$A/archives/partial" "$A/etc/preferences.d" "$T/cache/i386" "$T/i386"
  cat > "$A/etc/sources.list" <<EOF
deb [arch=i386] http://archive.ubuntu.com/ubuntu $CODENAME main universe
deb [arch=i386] http://archive.ubuntu.com/ubuntu $CODENAME-updates main universe
EOF
  cat > "$A/apt.conf" <<EOF
APT::Architecture "i386"; APT::Architectures { "i386"; };
Dir::State "$A"; Dir::State::Lists "$A/lists"; Dir::State::status "$A/status";
Dir::Cache "$A"; Dir::Etc::SourceList "$A/etc/sources.list"; Dir::Etc::SourceParts "-";
Dir::Etc::Preferences "$A/etc/preferences"; Dir::Etc::PreferencesParts "$A/etc/preferences.d";
Dir::Etc::Trusted "/etc/apt/trusted.gpg"; Dir::Etc::TrustedParts "/etc/apt/trusted.gpg.d";
EOF
  touch "$A/status"
  APT_CONFIG=$A/apt.conf apt-get update -qq 2>/dev/null
  (cd "$T/cache/i386" && grep -v '^#' "$R/scripts/packages/i386.txt" | while read -r p; do
     [ -n "$p" ] || continue
     ls "${p}"_*.deb >/dev/null 2>&1 || APT_CONFIG=$A/apt.conf apt-get download "$p" >/dev/null 2>&1 || echo "  (skip $p)"; done)
  for d in "$T"/cache/i386/*.deb; do dpkg-deb -x "$d" "$T/i386"; done
  mark "$T/i386"
fi

# ------------------------------------------------------------------ python helpers
step "python helpers (toolchain/venv: pyelftools, capstone)"
if [ ! -x "$T/venv/bin/python" ]; then
  python3 -m venv "$T/venv" && "$T/venv/bin/python" -m pip install -q pyelftools capstone pillow
fi

# ------------------------------------------------------------------ Ghidra (optional)
if [ "${1:-}" = "--ghidra" ] && ! done_mark "$T/ghidra"; then
  step "JDK 21 + Ghidra (toolchain/ghidra)"
  mkdir -p "$T/ghidra"
  (cd "$T/ghidra" &&
    curl -sL -o jdk.tgz "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_x64_linux_hotspot_21.0.12.1_1.tar.gz" &&
    tar xzf jdk.tgz && rm jdk.tgz &&
    curl -sL -o ghidra.zip "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_12.1.4_build/ghidra_12.1.4_PUBLIC_20260921.zip" &&
    python3 -c "import zipfile; zipfile.ZipFile('ghidra.zip').extractall('.')" && rm ghidra.zip)
  G=$(ls -d "$T"/ghidra/ghidra_*_PUBLIC)
  chmod +x "$G"/support/* "$G"/ghidraRun; find "$G" -path '*os/linux_x86_64/*' -type f -exec chmod +x {} +
  mark "$T/ghidra"
fi

# ------------------------------------------------------------------ from the cabinet
step "2008-era libraries from the cabinet (shared/cabinet-libs)"
if ! done_mark "$S/cabinet-libs"; then
  # third-party libs the engine was built against whose sonames/ABIs are gone from distros
  scripts/lib/extract-libs.sh "$S/cabinet-libs" libexpat.so.0 libsqlite.so.0 libsqlite3.so.0 \
      libssl.so.6 libpango-1.0.so.0 libpangoft2-1.0.so.0
  # (Allegro 4.0, which legacy games call directly, is not taken from here: the cabinet's
  # liballeg-4.0.0.so lacks its assembler drawing core, which lived in the loader executable.
  # src/legacy/allegro.cpp implements the subset the games use.)
  mark "$S/cabinet-libs"
fi

step "engine libraries the backend links against (shared/engine-sdk)"
if ! done_mark "$S/engine-sdk"; then
  scripts/lib/extract-libs.sh "$S/engine-sdk" libgame_device.so libgraphics.so libcore.so \
      libinput.so libmerit_sound.so libenums.so 2>/dev/null || true
  mark "$S/engine-sdk"
fi

step "cabinet data shared by all games (shared/data-common)"
if ! done_mark "$S/data-common"; then
  D=$S/data-common
  mkdir -p "$D/usr/local/gamedata" "$D/var-template/merit" "$D/etc" "$D/pango/modules"
  for d in config translations help ttf fonts; do cab_rdump root "/usr/local/gamedata/$d" "$D/usr/local/gamedata"; done
  for d in locale settings; do cab_rdump var "/merit/$d" "$D/var-template/merit"; done
  cab_dump home /maxx/.fonts.conf "$D/etc/fonts.conf"
  for m in $(cab_ls root /usr/lib/pango/1.5.0/modules | grep '\.so$' | grep -v basic-x); do
    cab_dump root "/usr/lib/pango/1.5.0/modules/$m" "$D/pango/modules/$m"
  done
  cab_dump root /etc/pango/i386-redhat-linux-gnu/pango.modules "$D/pango/pango.modules.tmp"
  grep -v basic-x "$D/pango/pango.modules.tmp" > "$D/pango/pango.modules.in"; rm "$D/pango/pango.modules.tmp"
  mark "$D"
fi

# the cabinet's fallback "default" game: game-over, winner/loser, quit and exit prompts per resolution
if [ ! -d "$S/data-common/usr/local/games/default" ]; then
  step "shared game screens (shared/data-common/usr/local/games/default)"
  cab_rdump root /usr/local/games/default "$S/data-common/usr/local/games"
fi

# shared assets of the legacy games (sounds, fonts, common images): gamegraphics/misc
if [ ! -d "$S/data-common/usr/local/gamedata/gamegraphics/misc" ]; then
  step "shared legacy game assets (shared/data-common/.../gamegraphics/misc)"
  mkdir -p "$S/data-common/usr/local/gamedata/gamegraphics"
  cab_rdump root /usr/local/gamedata/gamegraphics/misc "$S/data-common/usr/local/gamedata/gamegraphics"
fi

# downloadable content packs (photo hunt puzzles by year, shared picture sets): one copy for all
if [ ! -d "$S/data-common/usr/local/ion_only/content" ]; then
  step "content packs (shared/data-common/usr/local/ion_only/content)"
  mkdir -p "$S/data-common/usr/local/ion_only"
  cab_rdump ion /content "$S/data-common/usr/local/ion_only"
fi

# ------------------------------------------------------------------ shared runtime
step "assembling the 32-bit runtime (shared/runtime)"
if ! done_mark "$S/runtime"; then
  RT=$S/runtime
  mkdir -p "$RT"
  # glibc/libstdc++/libgcc from the multilib packages: shared objects only
  (cd "$T/sysroot/usr/lib32" && find . -maxdepth 1 \( -name '*.so.*' -o -name 'ld-linux.so.2' -o -name 'libgcc_s.so.1' \) -exec cp -a {} "$RT/" \;)
  cp -a "$T"/sysroot/usr/lib32/gconv "$RT/" 2>/dev/null || true
  # SDL2, Mesa, PulseAudio... (keeps sdl2-classic/, dri/, pulseaudio/ subfolders)
  cp -a "$T"/i386/usr/lib/i386-linux-gnu/. "$RT/"
  [ -d "$T/i386/lib/i386-linux-gnu" ] && cp -a "$T"/i386/lib/i386-linux-gnu/. "$RT/"
  find "$RT" -maxdepth 1 \( -name '*.a' -o -name '*.o' -o -name 'pkgconfig' -o -name 'cmake' \) -exec rm -rf {} +
  # 2008 libraries last (never their zlib)
  cp -a "$S"/cabinet-libs/. "$RT/"; rm -f "$RT/.done"
  mark "$RT"
fi

# the Unity 3.2 player shared by every Unity-family game, plus the 2008 libraries it needs
# that the runtime lacks (GLU, curl 3, FMOD Ex, Theora, gthread...)
step "Unity player (shared/unity)"
if ! done_mark "$S/unity"; then
  U=$S/unity
  mkdir -p "$U/lib"
  cab_dump ion /games/launcher/LinuxPlayer "$U/LinuxPlayer" && chmod +x "$U/LinuxPlayer"
  scripts/lib/extract-libs.sh "$U/closure" libGLU.so.1 libcurl.so.3 libfmodex.so libtheora.so.0 libgthread-2.0.so.0 2>/dev/null || true
  for f in "$U"/closure/*; do [ -e "$S/runtime/$(basename "$f")" ] || mv "$f" "$U/lib/"; done
  rm -rf "$U/closure"
  # the launcher's own lib/ (libsqlite3.so, which Mono's System.Data.SQLite P/Invokes as "sqlite3")
  cab_rdump ion /games/launcher/lib "$U"
  [ -f "$U/lib/libsqlite3.so" ] || true
  mark "$U"
fi

# ------------------------------------------------------------------ build
step "building megatouch-host + SDL2 backend (shared/bin)"
make -s -C "$R" build

echo
echo "setup complete. Next:  make new GAME=g_trix   then   make run GAME=g_trix"
