#!/usr/bin/env python3
"""Build docs/reference/games.md: every game on the cabinet with its GameId, library,
engine family and port status.

usage: catalog.py <repo root> <gameids dump> [per-game gamedata.xml ...]

Inputs (all in the repo / shared data):
  docs/data/games-catalogue.tsv       name, GameId, Active (from /var/merit/settings.xml)
  shared/.../gamedata.xml             master game table (DLLName, Directory, UseResolution)
  docs/data/engine-families.tsv       engine family per game library (readelf NEEDED scan)
  <gameids dump>                      "id<TAB>NAME" from shared/bin/gameids
"""
import os
import re
import sys

root, idsfile = sys.argv[1], sys.argv[2]


def tsv(path):
    with open(path, encoding='utf-8', errors='replace') as f:
        return [line.rstrip('\n').split('\t') for line in f if line.strip()]


ids = {name: num for num, name in tsv(idsfile)}
family = {so[:-3]: fam for fam, so in tsv(os.path.join(root, 'docs/data/engine-families.tsv'))}
gd = {}
# master table first; games added later carry their own gamedata.xml in their asset folder
texts = [open(os.path.join(root, 'shared/data-common/usr/local/gamedata/config/gamedata.xml'),
              encoding='utf-8', errors='replace').read()]
texts += [open(p, encoding='utf-8', errors='replace').read() for p in sys.argv[3:]]
for block in (b for t in texts for b in re.findall(r'<game>(.*?)</game>', t, re.S)):
    def tag(t):
        m = re.search(rf'<{t}>\s*(.*?)\s*</{t}>', block, re.S)
        return m.group(1) if m else ''
    gd.setdefault(tag('GameId'), (tag('DLLName'), tag('Directory'), tag('UseResolution')))

rows = []
for desc, gid, active in tsv(os.path.join(root, 'docs/data/games-catalogue.tsv')):
    dll, folder, res = gd.get(gid, (gid.lower(), gid.lower(), ''))
    if not dll:
        fam = 'service'          # menu/ad/online entries with no game library
    elif dll == 'launcher':
        fam = 'unity'            # Unity games all run through the shared launcher (LinuxPlayer)
    else:
        fam = family.get(dll, '')
    status = ''
    gdir = os.path.join(root, 'games', dll)
    if not os.path.isdir(gdir):        # Unity games are folders named after their Data dir
        gdir = os.path.join(root, 'games', folder)
    conf = os.path.join(gdir, 'game.conf')
    if os.path.isfile(conf):           # a ported game's game.conf beats the declared resolution
        kv = dict(l.strip().split('=', 1) for l in open(conf) if '=' in l and not l.startswith('#'))
        res = f"{kv.get('WIDTH', '')}x{kv.get('HEIGHT', '')}"
    if os.path.isfile(os.path.join(gdir, 'NOTES.md')):
        first = open(os.path.join(gdir, 'NOTES.md'), encoding='utf-8').read()
        m = re.search(r'Status:\s*\**([a-zA-Z ]+)', first)
        status = (m.group(1).strip() if m else 'started')
    res = {'SUPER_HIGH_RESOLUTION': '1280x800', 'HIGH_RESOLUTION': '1024x768?'}.get(res, res)
    rows.append((desc.title() if desc and desc != 'None' else gid, gid, ids.get(gid, '?'), dll, fam or 'unknown',
                 res.replace('RESOLUTION_', '') or '—', 'yes' if active == 'GAME_ACTIVE' else 'no', status))

fam_order = {'gamedevice': 0, 'unity': 1, 'merit3d': 2, 'legacy': 3, 'service': 4, 'unknown': 5}
rows.sort(key=lambda r: (fam_order.get(r[4], 9), r[0].lower()))
counts = {}
for r in rows:
    counts[r[4]] = counts.get(r[4], 0) + 1

out = os.path.join(root, 'docs/reference/games.md')
with open(out, 'w', encoding='utf-8') as f:
    f.write('# Game catalogue\n\n')
    f.write('Every game in the cabinet\'s operator settings (`/var/merit/settings.xml`), joined with the master\n'
            'game table (`gamedata.xml`), the engine family of its library and the engine\'s own GameId\n'
            'table. Generated by `tools/catalog.py` — re-run it after porting a game.\n\n')
    f.write('| Family | Games | What porting takes |\n| --- | ---: | --- |\n')
    what = {'gamedevice': 'shared SDL2 backend + a few loader stand-ins ([survey](gamedevice-survey.md))',
            'unity': 'the cabinet\'s Unity 3.2 player + launcher.xml + FMOD→PulseAudio shim ([unity](unity.md))',
            'merit3d': 'reimplement the loader\'s engine services (not started)',
            'legacy': 'the loader\'s 2D engine, reconstructed in src/legacy ([legacy](legacy.md))',
            'service': 'not a game: ads, online services, jukebox links',
            'unknown': 'library not found in /usr/local/lib'}
    for fam in sorted(counts, key=lambda k: fam_order.get(k, 9)):
        f.write(f'| {fam} | {counts[fam]} | {what.get(fam, "")} |\n')
    f.write('\n| Game | GameId | # | Library | Family | Resolution | Active | Port |\n'
            '| --- | --- | ---: | --- | --- | --- | --- | --- |\n')
    for r in rows:
        f.write(f'| {r[0]} | `{r[1]}` | {r[2]} | `{r[3]}` | {r[4]} | {r[5]} | {r[6]} | {r[7]} |\n')
print(f'wrote {out}: {len(rows)} games')
