#!/usr/bin/env python3
"""Generate placeholder definitions for a game's unresolved loader symbols.

usage: stubgen.py games/<name> <out.c>

Reads build/unresolved/<name>.txt (raw names, written by tools/analyze.sh) and writes a C file defining
every symbol, so the game can load while its loader services are still being written:
  * functions log their name the first time they are called and return 0;
  * data symbols are 64 KB of zeroes.
Functions vs data: a symbol reached through a PLT slot (R_386_JUMP_SLOT) in any of the game's
libraries is a function; otherwise a demangled name with an argument list is a function.

Stubs are a crutch: a function returning a float, a struct by value (hidden result pointer,
`ret 4`) or a pointer the caller dereferences will still misbehave. The first-call log says
which stub to replace with a real stand-in in src/legacy or src/host.
"""
import os
import subprocess
import sys

from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection

gd, out = sys.argv[1], sys.argv[2]
root = os.path.dirname(os.path.dirname(os.path.abspath(gd)))
with open(os.path.join(root, 'build/unresolved', os.path.basename(os.path.abspath(gd)) + '.txt')) as f:
    syms = sorted(set(l.strip() for l in f if l.strip()))

# never shadow what the port already implements
provided = set()
for lib in ('shared/bin/libmerit_legacy.so', 'shared/bin/megatouch-host'):
    path = os.path.join(root, lib)
    if os.path.exists(path):
        out_ = subprocess.run(['nm', '-D', '--defined-only', path], capture_output=True, text=True).stdout
        provided |= {l.split()[-1] for l in out_.splitlines() if l.strip()}
syms = [s for s in syms if s not in provided]

plt = set()
libdir = os.path.join(gd, 'lib')
for name in os.listdir(libdir):
    path = os.path.join(libdir, name)
    if os.path.islink(path) or not name.endswith('.so'):
        continue
    with open(path, 'rb') as fh:
        elf = ELFFile(fh)
        for sec in elf.iter_sections():
            if not isinstance(sec, RelocationSection):
                continue
            symtab = elf.get_section(sec['sh_link'])
            for r in sec.iter_relocations():
                if r['r_info_type'] == 7:            # R_386_JUMP_SLOT
                    plt.add(symtab.get_symbol(r['r_info_sym']).name)

demangled = subprocess.run(['c++filt'], input='\n'.join(syms), capture_output=True, text=True).stdout.split('\n')
lines = ['/* generated by tools/stubgen.py — do not edit; replace stubs with real stand-ins */',
         '#include <stdio.h>', '']
nf = nd = 0
for i, s in enumerate(syms):
    pretty = demangled[i] if i < len(demangled) else s
    is_func = s in plt or ('(' in pretty and not pretty.startswith(('typeinfo', 'vtable')))
    label = s.replace('"', '')
    esc = pretty.replace('\\', '\\\\').replace('"', '\\"')
    if is_func:
        nf += 1
        lines.append(f'int stub_f{i}(void) __asm__("{label}");')
        lines.append(f'int stub_f{i}(void) {{ static int n; if (!n++) fprintf(stderr, "[stub] %s\\n", "{esc}"); return 0; }}')
    else:
        nd += 1
        lines.append(f'char stub_d{i}[65536] __asm__("{label}") __attribute__((aligned(16))); /* {esc} */')
with open(out, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f'{out}: {nf} functions, {nd} data symbols')
