#!/bin/bash
# Survey every GameDevice-engine game in the cabinet without scaffolding it: extract its
# library closure to a temp folder and list the loader symbols that would still be missing
# with today's src/host + backend. Writes docs/reference/gamedevice-survey.md.
#
#   tools/survey.sh            (takes a few minutes: one extraction per game)
set -uo pipefail
export LC_ALL=C
R=$(cd "$(dirname "$0")/.." && pwd)
. "$R/cabinet.conf"; . "$R/scripts/lib/cabinet.sh"; cab_check || exit 1
OUT="$R/docs/reference/gamedevice-survey.md"
W=$(mktemp -d); trap 'rm -rf "$W"' EXIT
MASTER="$R/shared/data-common/usr/local/gamedata/config/gamedata.xml"
gid() { LD_LIBRARY_PATH="$R/shared/engine-sdk:$R/shared/runtime" "$R/shared/runtime/ld-linux.so.2" "$R/shared/bin/gameids" "$1" 2>/dev/null; }
defined() { { nm -D --defined-only "$@" 2>/dev/null || true; } | awk 'NF>=3 {print $3}' | sed 's/@.*//'; }

# what the shared pieces provide (once)
{ for f in "$R"/shared/runtime/*.so* "$R"/shared/runtime/pulseaudio/*.so*; do [ -f "$f" ] && defined "$f"; done
  defined "$R/shared/bin/megatouch-host" "$R/shared/bin/libgame_device_sprite.so"; } | sort -u > "$W/base"

rows=()
for so in $(awk -F'\t' '$1=="gamedevice"{print $2}' "$R/docs/data/engine-families.tsv"); do
  dll=${so%.so}
  [ "$dll" = launcher ] && continue
  printf '  %s\n' "$dll" >&2
  info=$(python3 -I "$R/tools/gameinfo.py" "$dll" "$MASTER" 2>/dev/null) || {
    cab_dump ion "/games/$dll/gamedata.xml" "$W/gd.xml" 2>/dev/null
    info=$(python3 -I "$R/tools/gameinfo.py" "$dll" "$W/gd.xml" 2>/dev/null) || info="GAMEID_NAME= DLL=$dll DIR=$dll DESC=$dll RES="; }
  GAMEID_NAME=; DIR=; DESC=; RES=; eval "$info"
  L="$W/$dll"; mkdir -p "$L"
  "$R/scripts/lib/extract-libs.sh" "$L" "$so" 2>/dev/null
  rm -f "$L"/{libgame_device_sprite,libgraphics_sprite,libinput_sprite,libsound_sprite,libmerit2d,libmerit3d,libmeritbasegame,libmerit_threads}.so
  { cat "$W/base"; for f in "$L"/*.so*; do defined "$f"; done; } | sort -u > "$W/def"
  for f in "$L"/*.so; do nm -D --undefined-only "$f" 2>/dev/null | awk '$1=="U"{print $2}'; done | sed 's/@.*//' | sort -u > "$W/undef"
  missing=$(join -v1 "$W/undef" "$W/def" | c++filt | sed 's/(.*//' | sort -u | tr '\n' ',' | sed 's/,$//; s/,/, /g')
  n=$(join -v1 "$W/undef" "$W/def" | wc -l)
  extra=$(comm -23 <(ls "$L" | sort) <(ls "$R/shared/engine-sdk" | sort) | grep -vx "$so" | tr '\n' ' ')
  assets=none
  cab_exists ion "/games/$DIR" && assets="ion_only/games/$DIR"
  [ "$assets" = none ] && cab_exists root "/usr/local/games/$DIR" && assets="usr/local/games/$DIR"
  status=""; [ -d "$R/games/$dll/lib" ] && status="ported"
  case $RES in SUPER_HIGH_RESOLUTION) RES=1280x800;; HIGH_RESOLUTION) RES="1024x768?";; RESOLUTION_*) RES=${RES#RESOLUTION_};; esac
  id=$(gid "$GAMEID_NAME"); [ -n "$id" ] || id="?"
  rows+=("$n|$DESC|$dll|${GAMEID_NAME:-?} = $id|${RES:-—}|$assets|${extra:-—}|${missing:-—}|$status")
  rm -rf "$L"
done

{
  echo "# GameDevice games: porting survey"
  echo
  echo "Generated by \`tools/survey.sh\` on $(date +%F). For every game built on the same engine as Trix,"
  echo "the loader functions still missing with the current \`src/host\` + backend, sorted easiest first."
  echo "Re-run after adding stand-ins: a symbol added for one game disappears from every row."
  echo
  echo "| Missing | Game | DLL | GameId | Resolution | Assets | Extra engine libs | Missing symbols | |"
  echo "| ---: | --- | --- | --- | --- | --- | --- | --- | --- |"
  printf '%s\n' "${rows[@]}" | sort -t'|' -k1,1n | awk -F'|' '{printf "| %s | %s | `%s` | %s | %s | %s | %s | %s | %s |\n",$1,$2,$3,$4,$5,$6,$7,$8,$9}'
  echo
  echo "\"Missing\" counts unique symbols. Data symbols must exist before the game loads; functions"
  echo "only crash when called, but megatouch-host loads with RTLD_NOW, so all must be provided."
  echo "Common groups: \`ustr*\`/\`u*\` = Allegro Unicode helpers; \`WorldClass\`/\`Sprite\`/\`Bitmap\` = the"
  echo "legacy sprite engine (much bigger job); \`HighScoresManager\`/\`LanguageManager\` = small services."
} > "$OUT"
echo "wrote $OUT" >&2
